version: "3.7"
services:
  postgres_database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  prefect_server:
    image: python_prefect_dbt_piperider
    restart: always
    volumes:
      - prefect:/.prefect
      - .:${PREFECT_LOCAL_STORAGE_PATH}
    entrypoint:
      [ 
        "prefect", "server", "start", 
        "--host", "0.0.0.0", 
        "--port", "4200" 
      ]
    environment:
      - PREFECT_ORION_API_HOST=${PREFECT_ORION_API_HOST}
      - PREFECT_ORION_API_PORT=${PREFECT_ORION_API_PORT}
      - PREFECT_ORION_UI_API_URL=${PREFECT_ORION_UI_API_URL}
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      - PREFECT_LOCAL_STORAGE_PATH=${PREFECT_LOCAL_STORAGE_PATH}
    ports:
      - 4200:4200
    depends_on:
      - postgres_database
  
  prefect_agent:
    image: python_prefect_dbt_piperider
    restart: always
    volumes:
      - .:${PREFECT_LOCAL_STORAGE_PATH}
    entrypoint: 
      [ 
        "prefect", "agent", "start", 
        "-q", "default" 
      ]
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
      - PREFECT_LOCAL_STORAGE_PATH=${PREFECT_LOCAL_STORAGE_PATH}
    
  prefect_job:
    image: python_prefect_dbt_piperider
    volumes:
      - .:${PREFECT_LOCAL_STORAGE_PATH}
    entrypoint: 
      [ 
        "/opt/venv/bin/python" 
      ]
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
      - PREFECT_LOCAL_STORAGE_PATH=${PREFECT_LOCAL_STORAGE_PATH}     
    
volumes:
  prefect:
  postgres_db:
networks:
  default:
    name: prefect-network    