version: "3.7"
x-function: &function
  image: python_prefect_dbt_piperider
  restart: always
  volumes:
    - .:${PREFECT_LOCAL_STORAGE_PATH}
  environment:
    - PREFECT_LOCAL_STORAGE_PATH=${PREFECT_LOCAL_STORAGE_PATH}
    - PREFECT_API_URL=${PREFECT_API_URL} 

services:
  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    volumes:
      - postgres_db:/var/lib/postgresql/data

  server:
    <<: *function
    entrypoint:
      [ 
        "prefect", "server", "start", 
        "--host", "0.0.0.0", 
        "--port", "4200" 
      ]
    environment:
      - PREFECT_ORION_API_HOST=${PREFECT_ORION_API_HOST}
      - PREFECT_ORION_API_PORT=${PREFECT_ORION_API_PORT}
      - PREFECT_ORION_UI_API_URL=${PREFECT_ORION_UI_API_URL}
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      - PREFECT_LOCAL_STORAGE_PATH=${PREFECT_LOCAL_STORAGE_PATH}
    ports:
      - 4200:4200
    depends_on:
      - db
  
  agent:
    <<: *function
    entrypoint: 
      [ 
        "prefect", "agent", "start", 
        "-q", "default" 
      ]
    depends_on:
      - server
  
  bash:
    <<: *function
    entrypoint: [ "bash" ]

  python:
    <<: *function
    entrypoint: [ "python" ]
  
  dbt:
    <<: *function
    entrypoint: [ "dbt" ]

  piperider:
    <<: *function
    entrypoint: [ "piperider" ]
     
volumes:
  prefect:
  postgres_db:

networks:
  default:
    name: prefect-network    